### PR TITLE
update sampling from the deck

### PR DESCRIPTION
**Pull request by rocky-d**
The old way of sampling from the deck has a flaw.
The player and the opponent have the chance getting the same card, which means they can refer to one same object (the card). That can lead to a confusing change of "Health" and "Defense".
The new way avoids sampling the same card, which should be understandable.

### CODE REVIEW

**Comment by prabhatram** [comment]
Could you elaborate on the 'confusing change of "Health" and "Defense"'?

**Comment by rocky-d** [comment]
> Could you elaborate on the 'confusing change of "Health" and "Defense"'?

Try to run this:

```python
deck = [
    {
        'Name': 'Rocky',
        'Health': 100,
    },
]

# assume player and opponent get the same card
player_card = deck[0]  # assume this means sampling
opponent_card = deck[0]  # assume this means sampling

player_card['Health'] -= 10  # player gets attacked

print(player_card['Health'])  # 90
print(opponent_card['Health'])  # 90

```

The output will be two "90", because they refer to the same object.

**Comment by prabhatram** [comment]
Got it. You're right. It's the same object, because they both are drawing from the same list. Your alternative approach is fine, but it kind of violates the fairness rule of the game. For instance, if the player gets a really powerful card randomly, then that would mean the opponent won't. So, it's just unfair.

So, to keep the game fair, and give everyone an equal chance of winning, another solution is to create deep copies using Python's copy module(copy.deepcopy(card_deck)). This will create a completely independent object of the original list.

**Comment by rocky-d** [comment]
> Got it. You're right. It's the same object, because they both are drawing from the same list. Your alternative approach is fine, but it kind of violates the fairness rule of the game. For instance, if the player gets a really powerful card randomly, then that would mean the opponent won't. So, it's just unfair.
> 
> So, to keep the game fair, and give everyone an equal chance of winning, another solution is to create deep copies using Python's copy module(copy.deepcopy(card_deck)). This will create a completely independent object of the original list.

```python
player_deck = copy.deepcopy(random.sample(card_deck, deck_size))
opponent_deck = copy.deepcopy(random.sample(card_deck, deck_size))
```

**Pull request closed without merging**
